// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDLePBN6BIShDD-2g8L4kp11K-NSpR6zQ',
    appId: '1:731298787135:web:54995ed5de74ae3391ad8a',
    messagingSenderId: '731298787135',
    projectId: 'fuel-wallet-12224',
    authDomain: 'fuel-wallet-12224.firebaseapp.com',
    storageBucket: 'fuel-wallet-12224.firebasestorage.app',
    measurementId: 'G-YSE29ZX2PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkFAs7t8RNseMaFe7udC3BcpvGBpBK16w',
    appId: '1:731298787135:android:ace56032b7f8ff6691ad8a',
    messagingSenderId: '731298787135',
    projectId: 'fuel-wallet-12224',
    storageBucket: 'fuel-wallet-12224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4T8SBVfaGoH6w7pERpVoYEaZYU2H2NBA',
    appId: '1:731298787135:ios:2f7be10c13836d4b91ad8a',
    messagingSenderId: '731298787135',
    projectId: 'fuel-wallet-12224',
    storageBucket: 'fuel-wallet-12224.firebasestorage.app',
    iosBundleId: 'com.example.carMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4T8SBVfaGoH6w7pERpVoYEaZYU2H2NBA',
    appId: '1:731298787135:ios:2f7be10c13836d4b91ad8a',
    messagingSenderId: '731298787135',
    projectId: 'fuel-wallet-12224',
    storageBucket: 'fuel-wallet-12224.firebasestorage.app',
    iosBundleId: 'com.example.carMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDLePBN6BIShDD-2g8L4kp11K-NSpR6zQ',
    appId: '1:731298787135:web:d53c914a6a5d17b991ad8a',
    messagingSenderId: '731298787135',
    projectId: 'fuel-wallet-12224',
    authDomain: 'fuel-wallet-12224.firebaseapp.com',
    storageBucket: 'fuel-wallet-12224.firebasestorage.app',
    measurementId: 'G-1MQS8CB4D5',
  );
}
